modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
logoFile = "logo.png"
[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    updateJSONURL = "https://update.mc.vanilla.xin/${mod_id}/neoforge/${minecraft_version}" #optional
    displayURL = "https://mc.vanilla.xin/${mod_id}"
    authors = "${mod_authors}"
    description = '''${mod_description}'''
    clientRequired = false
[[mixins]]
    config = "${mod_id}.mixins.json"
[[dependencies."${mod_id}"]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies."${mod_id}"]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies."${mod_id}"]]
    modId = "${mod_id}"
    mandatory = true
    versionRange = "[1.0.0,)"
    ordering = "NONE"
    side = "SERVER"
[[dependencies."${mod_id}"]]
    modId = "${mod_id}"
    mandatory = false
    versionRange = "[1.0.0,)"
    ordering = "NONE"
    side = "CLIENT"
